# Language is rust because we depend on spinning up the server to run tests,
# and it's easier to get python up and running in a rust test environment than
# the other way around in TravisCI.
language: rust
cache:
  pip: true
  directories:
    - .tox
    - venv
sudo: required
dist: trusty

git:
  submodules: false

install: ./ci/install.sh
script: make venv test
env:
  matrix:
    - TOXENV=py2
    - TOXENV=py3
